version: "3.9"

services:
    cargo_processing_api:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"