apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "aks-sb-azmonitor-microservices.fullname" . }}
  labels:
    {{- include "aks-sb-azmonitor-microservices.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.aksKeyVaultSecretProviderIdentityId }}
    keyvaultName: {{ .Values.keyVault.name }}
    cloudName: ""         
    objects:  |
      array:
        - |
          objectName: AppInsightsConnectionString
          objectType: secret
        - |
          objectName: ServiceBusConnectionString
          objectType: secret
        - |
          objectName: CosmosDBEndpoint
          objectType: secret
        - |
          objectName: CosmosDBKey
          objectType: secret
    tenantId: {{ .Values.keyVault.tenantId }}
  secretObjects:
  - data:
      - key: AppInsightsConnectionString
        objectName: AppInsightsConnectionString
      - key: ServiceBusConnectionString
        objectName: ServiceBusConnectionString
      - key: CosmosDBEndpoint
        objectName: CosmosDBEndpoint
      - key: CosmosDBKey
        objectName: CosmosDBKey
    secretName: invalid-cargo-manager-secrets
    type: Opaque 